### ISSUE TITLE
Consider adding to DefinitelyTyped

### ISSUE THREAD

**Issue by rianadon** [mattvperry/typed-scoped-http-client#1]
Hi! I just came across this project while writing typings for Hubot (which uses the `scoped-http-client` module), and it was so absolutely helpful that I didn't have to write declaration files for another module. Thanks so much for writing this!

However, it looks like the project uses the deprecated [typings](https://github.com/typings/typings) project, so I had to end up copying your code into a type declaration file rather than installing the typings via a package manager or some nicer method.

Therefore, it would be awesome if you could submit the typings to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped). Or if you don't have the time, I'd be willing to do so and credit you as the author.

Thanks!

**Comment by mattvperry** [comment]
Yeah, I wrote these types for a hubot project as well. However, I wrote these a very long time ago for the old `typings` project before the `@types/` scope was the standard. I don't think these types are complete and I haven't used them in years. Feel free to use them to submit your own contribution to DefinitelyTyped if you'd like.

**Comment by rianadon** [comment]
They've worked for me and the `scoped-http-client` module hasn't been updated in 3 years, so the typings are probably fine. I'll submit them and see where they go. Thanks for responding so quickly!

**Comment by rianadon** [comment]
The DefinitelyTyped pull request is DefinitelyTyped/DefinitelyTyped#26240 if you're curious.
